//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Create_cshtml : DotNetNuke.Web.Mvc.Framework.DnnWebViewPage<Dnn.Bce.Dnn.Idopontfoglalas.Models.ReservationEntity> {
private static object @__o;
#line hidden
public _Page_Create_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
private void @__RazorDesignTimeHelpers__() {
#pragma warning disable 219

#line 1 "C:\Users\USER\AppData\Local\Temp\2E2AF13586878B00E2048FFFEE17A6D5087C\2\idopontfoglalas-modul\Dnn.Idopontfoglalas\Views\Reservation\Create.cshtml"
          DotNetNuke.Web.Mvc.Framework.DnnWebViewPage<Dnn.Bce.Dnn.Idopontfoglalas.Models.ReservationEntity> __inheritsHelper = null;


#line default
#line hidden
#pragma warning restore 219
}
public override void Execute() {

#line 2 "C:\Users\USER\AppData\Local\Temp\2E2AF13586878B00E2048FFFEE17A6D5087C\2\idopontfoglalas-modul\Dnn.Idopontfoglalas\Views\Reservation\Create.cshtml"
  
    ViewBag.Title = "Új foglalás létrehozása";


#line default
#line hidden

#line 3 "C:\Users\USER\AppData\Local\Temp\2E2AF13586878B00E2048FFFEE17A6D5087C\2\idopontfoglalas-modul\Dnn.Idopontfoglalas\Views\Reservation\Create.cshtml"
   __o = Html.AntiForgeryToken();


#line default
#line hidden

#line 4 "C:\Users\USER\AppData\Local\Temp\2E2AF13586878B00E2048FFFEE17A6D5087C\2\idopontfoglalas-modul\Dnn.Idopontfoglalas\Views\Reservation\Create.cshtml"
              __o = Dnn.ActiveModule.ModuleID;


#line default
#line hidden
}
}
}
