//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

#line 2 "C:\Users\USER\AppData\Local\Temp\2E2AF13586878B00E2048FFFEE17A6D5087C\2\idopontfoglalas-modul\Dnn.Idopontfoglalas\Views\Reservation\Index.cshtml"
using DotNetNuke.Web.Client.ClientResourceManagement;

#line default
#line hidden

#line 3 "C:\Users\USER\AppData\Local\Temp\2E2AF13586878B00E2048FFFEE17A6D5087C\2\idopontfoglalas-modul\Dnn.Idopontfoglalas\Views\Reservation\Index.cshtml"
using DotNetNuke.Framework.JavaScriptLibraries;

#line default
#line hidden

#line 4 "C:\Users\USER\AppData\Local\Temp\2E2AF13586878B00E2048FFFEE17A6D5087C\2\idopontfoglalas-modul\Dnn.Idopontfoglalas\Views\Reservation\Index.cshtml"
using DotNetNuke.Entities.Users;

#line default
#line hidden

#line 5 "C:\Users\USER\AppData\Local\Temp\2E2AF13586878B00E2048FFFEE17A6D5087C\2\idopontfoglalas-modul\Dnn.Idopontfoglalas\Views\Reservation\Index.cshtml"
using DotNetNuke.Web.Mvc.Helpers;

#line default
#line hidden

public class _Page_Index_cshtml : DotNetNuke.Web.Mvc.Framework.DnnWebViewPage<IEnumerable<Dnn.Bce.Dnn.Idopontfoglalas.Models.ReservationEntity>> {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
private void @__RazorDesignTimeHelpers__() {
#pragma warning disable 219

#line 1 "C:\Users\USER\AppData\Local\Temp\2E2AF13586878B00E2048FFFEE17A6D5087C\2\idopontfoglalas-modul\Dnn.Idopontfoglalas\Views\Reservation\Index.cshtml"
          DotNetNuke.Web.Mvc.Framework.DnnWebViewPage<IEnumerable<Dnn.Bce.Dnn.Idopontfoglalas.Models.ReservationEntity>> __inheritsHelper = null;


#line default
#line hidden
#pragma warning restore 219
}
public override void Execute() {

#line 6 "C:\Users\USER\AppData\Local\Temp\2E2AF13586878B00E2048FFFEE17A6D5087C\2\idopontfoglalas-modul\Dnn.Idopontfoglalas\Views\Reservation\Index.cshtml"
  
    ViewBag.Title = "Foglalások listája";
    var currentUser = UserController.Instance.GetCurrentUserInfo();


#line default
#line hidden

#line 7 "C:\Users\USER\AppData\Local\Temp\2E2AF13586878B00E2048FFFEE17A6D5087C\2\idopontfoglalas-modul\Dnn.Idopontfoglalas\Views\Reservation\Index.cshtml"
                                    __o = Url.Action("Create", "Reservation");


#line default
#line hidden

#line 8 "C:\Users\USER\AppData\Local\Temp\2E2AF13586878B00E2048FFFEE17A6D5087C\2\idopontfoglalas-modul\Dnn.Idopontfoglalas\Views\Reservation\Index.cshtml"
    if (!Model.Any())
    {
        

#line default
#line hidden

#line 9 "C:\Users\USER\AppData\Local\Temp\2E2AF13586878B00E2048FFFEE17A6D5087C\2\idopontfoglalas-modul\Dnn.Idopontfoglalas\Views\Reservation\Index.cshtml"
              
    }
    else
    {
        

#line default
#line hidden

#line 10 "C:\Users\USER\AppData\Local\Temp\2E2AF13586878B00E2048FFFEE17A6D5087C\2\idopontfoglalas-modul\Dnn.Idopontfoglalas\Views\Reservation\Index.cshtml"
                    foreach (var reservation in Model)
                    {
                        

#line default
#line hidden

#line 11 "C:\Users\USER\AppData\Local\Temp\2E2AF13586878B00E2048FFFEE17A6D5087C\2\idopontfoglalas-modul\Dnn.Idopontfoglalas\Views\Reservation\Index.cshtml"
                           __o = reservation.ID;


#line default
#line hidden

#line 12 "C:\Users\USER\AppData\Local\Temp\2E2AF13586878B00E2048FFFEE17A6D5087C\2\idopontfoglalas-modul\Dnn.Idopontfoglalas\Views\Reservation\Index.cshtml"
                           __o = reservation.Name;


#line default
#line hidden

#line 13 "C:\Users\USER\AppData\Local\Temp\2E2AF13586878B00E2048FFFEE17A6D5087C\2\idopontfoglalas-modul\Dnn.Idopontfoglalas\Views\Reservation\Index.cshtml"
                           __o = reservation.Email;


#line default
#line hidden

#line 14 "C:\Users\USER\AppData\Local\Temp\2E2AF13586878B00E2048FFFEE17A6D5087C\2\idopontfoglalas-modul\Dnn.Idopontfoglalas\Views\Reservation\Index.cshtml"
                           __o = reservation.Phone;


#line default
#line hidden

#line 15 "C:\Users\USER\AppData\Local\Temp\2E2AF13586878B00E2048FFFEE17A6D5087C\2\idopontfoglalas-modul\Dnn.Idopontfoglalas\Views\Reservation\Index.cshtml"
                           __o = reservation.Time;


#line default
#line hidden

#line 16 "C:\Users\USER\AppData\Local\Temp\2E2AF13586878B00E2048FFFEE17A6D5087C\2\idopontfoglalas-modul\Dnn.Idopontfoglalas\Views\Reservation\Index.cshtml"
                           __o = reservation.Quantity;


#line default
#line hidden

#line 17 "C:\Users\USER\AppData\Local\Temp\2E2AF13586878B00E2048FFFEE17A6D5087C\2\idopontfoglalas-modul\Dnn.Idopontfoglalas\Views\Reservation\Index.cshtml"
                            __o = reservation.IsActive == true ? "Igen" : "Nem";


#line default
#line hidden

#line 18 "C:\Users\USER\AppData\Local\Temp\2E2AF13586878B00E2048FFFEE17A6D5087C\2\idopontfoglalas-modul\Dnn.Idopontfoglalas\Views\Reservation\Index.cshtml"
                                if (reservation.IsActive == true && (reservation.CreatedBy == currentUser.UserID || currentUser.IsInRole("Administrators")))
                                {
                                    
#line default
#line hidden

#line 19 "C:\Users\USER\AppData\Local\Temp\2E2AF13586878B00E2048FFFEE17A6D5087C\2\idopontfoglalas-modul\Dnn.Idopontfoglalas\Views\Reservation\Index.cshtml"
                                              
                                }

ine default
#line hidden

#line 20 "C:\Users\USER\AppData\Local\Temp\2E2AF13586878B00E2048FFFEE17A6D5087C\2\idopontfoglalas-modul\Dnn.Idopontfoglalas\Views\Reservation\Index.cshtml"
                           
                    }

#line default
#line hidden

#line 24 "21\Users\USER\AppData\Local\Temp\2E2AF13586878B00E2048FFFEE17A6D5087C\2\idopontfoglalas-modul\Dnn.Idopontfoglalas\Views\Reservation\Index.cshtml"
              
    }

#line default
#line hidden

#line 25 "22\Users\USER\AppData\Local\Temp\2E2AF13586878B00E2048FFFEE17A6D5087C\2\idopontfoglalas-modul\Dnn.Idopontfoglalas\Views\Reservation\Index.cshtml"
              __o = Dnn.ActiveModule.ModuleID;


#line default
#line hidden

#line 26 "23\Users\USER\AppData\Local\Temp\2E2AF13586878B00E2048FFFEE17A6D5087C\2\idopontfoglalas-modul\Dnn.Idopontfoglalas\Views\Reservation\Index.cshtml"
                             __o = Dnn.ActiveModule.ModuleID;


#line default
#line hidden
}
}
}
